---
abstract: 'Scripts and Modules to manage PTC(R) ProE/Engineer(R) / Creo(TM) configurations. Use perldoc CAD::Firemen to get an introduction to the usage of this distribution.'
author:
  - 'Joachim Langenbach <langenbach@imw.tu-clausthal.de>'
build_requires:
  Capture::Tiny: 0
  File::Basename: 0
  FindBin: 0
  Test::More: 0.88
  Test::Script: 1.05
  blib: 0
  lib: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.132140'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CAD-Firemen
requires:
  Archive::Zip: 0
  DBI: 0
  Digest::MD5: 0
  Exporter: 0
  File::Copy: 0
  File::Copy::Recursive: 0
  File::Find: 0
  File::Path: 0
  File::Spec: 0
  Getopt::Long: 0
  HTML::TreeBuilder: 0
  POSIX: 0
  Term::ANSIColor: 0
  Term::ProgressBar: 0
  Term::ReadKey: 0
  Tie::File: 0
  Win32: 0
  Win32::Console::ANSI: 0
  Win32::Shortcut: 0
  XML::LibXML: 0
  YAML::XS: 0
  constant: 0
  strict: 0
  warnings: 0
version: 0.5.4
